app/models/Users.py
from datetime import datetime, timezone
from sqlalchemy.dialects.postgresql import TIMESTAMP
from flask_login import UserMixin

from app import db

class Users(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(), nullable=False, unique=True)
    password = db.Column(db.String(), nullable=False)
    type = db.Column(db.Enum('Admin', 'API', name='user_types'), nullable=False)
    email = db.Column(db.String(), nullable=True, unique=True)
    phone = db.Column(db.String(), nullable=True, unique=True)
    details = db.Column(db.Text, nullable=True)
    created_at = db.Column(
        TIMESTAMP(timezone=True), 
        default=lambda: datetime.now(timezone.utc), 
        nullable=False
    )
    updated_at = db.Column(
        TIMESTAMP(timezone=True), 
        default=lambda: datetime.now(timezone.utc), 
        onupdate=lambda: datetime.now(timezone.utc), 
        nullable=False
    )

    user_roles = db.relationship(
        'UsersRole',
        backref='user_roles',
        cascade='all, delete-orphan'
    )

    def __repr__(self):
        return f"<User {self.username}>"
    

# SQL create table scripts
# CREATE TYPE user_types AS ENUM ('Admin', 'API');

# CREATE TABLE users (
#     id SERIAL PRIMARY KEY,
#     username VARCHAR NOT NULL UNIQUE,
#     email VARCHAR NULL UNIQUE,
#     phone VARCHAR NULL UNIQUE,
#     password VARCHAR NOT NULL,
#     api_token VARCHAR UNIQUE,
#     type user_types NOT NULL,
#     details TEXT,
#     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
#     updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
# );

app/routes/shared.py
from datetime import datetime, timezone
from flask import Blueprint, request, jsonify, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash

from app import db
from app import login_manager
from ..models import Users, Roles

shared = Blueprint('shared', __name__, template_folder='templates', static_folder='static')

@login_manager.user_loader
def load_user(uid):
    user = Users.query.get(int(uid))
    return user

@login_manager.unauthorized_handler
def unauthorized_callback():
    return redirect(url_for('shared.signin_view'))

@shared.route('/')
@login_required
def dashboard_view():
    if current_user.is_authenticated:
        return render_template('users/dashboard.html')
    else:
        return redirect(url_for('shared.signin_view'))


@shared.route('/create_account', methods=['GET', 'POST'])
@login_required
def create_account():
    return render_template('users/createaccount.html')

@shared.route('/update_account', methods=['GET', 'POST'])
@login_required
def update_account():
    return render_template('users/updateaccount.html')

@shared.route('/user_list', methods=['GET', 'POST'])
@login_required
def user_list():
    return render_template('users/accountlist.html')

@shared.route('/create_roles', methods=['GET', 'POST'])
@login_required
def create_roles():
    return render_template('users/createroles.html')


@shared.route('/api_list', methods=['GET', 'POST'])
@login_required
def api_list():
    role_name = request.args.get('role_name', None)
    return render_template('users/apilist.html', set_role_name=role_name)


@shared.route('/create_superuser', methods=['POST'])
def create_superuser():
    data = request.get_json()
    # print(data)

    if not data:
        return jsonify({'error': 'Missing JSON data'}), 400

    username = data.get('username')
    password = data.get('password')
    user_type = data.get('type')
    email = data.get('email') if data.get('email') else None
    phone = data.get('phone') if data.get('phone') else None

    if not username or not password or not user_type:
        return jsonify({'error': 'All fields are required'}), 400

    if user_type != 'Admin':
        return jsonify({'error': 'Invalid superuser type'}), 400

    if Users.query.filter(Users.username == username).first():
        return jsonify({'error': 'Username already exists'}), 409

    hashed_password = generate_password_hash(password)
    new_user = Users(
        username=username,
        password=hashed_password,
        type=user_type,
        email=email,
        phone = phone,
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc)
    )
    db.session.add(new_user)
    db.session.commit()

    return jsonify({'message': 'User registered successfully'}), 201




@shared.route('/signin', methods=['GET', 'POST'])
def signin_view():
    if request.method == 'GET':
        return render_template('users/signin.html')
    
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = Users.query.filter(Users.username == username).first()
        if user.type != 'Admin':
            flash("Invalid username type, please try again!", 'error')
            return redirect(url_for('shared.signin_view'))
        
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('shared.dashboard_view'))

        else:
            flash("Invalid username or password, please try again!", 'error')
            return redirect(url_for('shared.signin_view'))



@shared.route('/signout')
def signout_view():
    logout_user()
    return redirect(url_for('shared.signin_view'))

        

app/templates/users/accountlist.html
{% extends "base.html" %}
{% block title %}User Accounts{% endblock %}

{% block content %}
<div class="m-2">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center ms-2 pt-2 pb-3">
        <h4 >API Users</h4>
    </div>

    <div class="container-fluid border border-1 rounded-1 p-4">
        <form>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label for="filter_username" class="text-muted mb-1">Username</label>
                    <input type="text" class="form-control" id="filter_username" placeholder="Username">
                </div>
                <div class="form-group col-lg-6">
                    <label for="filter_user_type" class="text-muted mb-1">User Type</label>
                    <select class="form-control" id="filter_user_type">
                        <option value="">Select Type</option>
                        <option value="Admin" {% if current_user.type == 'Admin' %} disabled {% endif %}>Admin</option>
                        <option value="API">API</option>
                    </select>
                </div>
                <!-- <div class="form-group col-lg-4">
                    <label for="roles">Roles</label>
                    <input type="text" class="form-control" id="roles" placeholder="Roles">
                </div> -->
            </div>
            <div class="d-flex gap-2 justify-content-end mt-2">
                <button type="button" class="btn btn-outline-warning col-lg-1" onclick="reset_api_user_filter()">Reset</button>
                <button type="button" class="btn btn-secondary col-lg-1" onclick="get_api_user_list()">Filter</button>
            </div>
        </form>
    </div>

    <div class="mt-2 container-fluid border border-1 rounded-1 p-4">
        <div class="d-flex justify-content-end mb-2">
            <a type="submit" class="btn btn-success" href="{{ url_for('shared.create_account') }}"><i class="fa-solid fa-plus"></i> Create</a>
        </div>
        <div class="table-responsive small">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">Username</th>
                        <th scope="col">User Type</th>
                        <th scope="col">Roles</th>
                        <th scope="col">Created At</th>
                        <th class="text-end" scope="col">Action</th>
                    </tr>
                </thead>
                <tbody id="tbody_api_user_list">
                    <!-- table body data will add by js -->
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script>
        const updateUserUrl = "{{ url_for('shared.update_account') }}";
    </script>
    <script src="../../static/js/account.js"></script>
{% endblock %}

app/templates/users/apilist.html
{% extends "base.html" %}
{% block title %}API's{% endblock %}

{% block content %}
<div class="m-2">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center ms-2 pt-2 pb-3">
        <h4 >API's</h4>
    </div>

    <div class="container-fluid border border-1 rounded-1 p-4">
        <form>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label for="filter_api_role" class="text-muted mb-2">Role</label>
                    <select class="js-example-basic-single form-control" id="filter_api_role" name="state">
                        <!-- option will ad by js -->
                    </select>
                </div>
                <div class="form-group col-lg-6">
                    <label for="filter_api_type" class="text-muted mb-2">API Type</label>
                    <select class="form-control" id="filter_api_type" style="padding: 0.1rem .75rem !important;">
                        <option value="">Select Type</option>
                        <option value="GET">GET</option>
                        <option value="POST">POST</option>
                        <option value="PUT">PUT</option>
                        <option value="HEAD">HEAD</option>
                        <option value="DELETE">DELETE</option>
                        <option value="PATCH">PATCH</option>
                        <option value="OPTIONS">OPTIONS</option>
                        <option value="CONNECT">CONNECT</option>
                        <option value="TRACE">TRACE</option>
                    </select>
                </div>
            </div>


            <div class="form-group mt-3">
                <label for="filter_api_link" class="text-muted mb-2">API</label>
                <input type="text" class="form-control" id="filter_api_link" placeholder="API Link">
            </div>


            <div class="d-flex gap-2 justify-content-end my-2">
                <button type="button" class="btn btn-outline-secondary col-lg-1" onclick="reset_api_filter()">Reset</button>
                <button type="button" class="btn btn-primary col-lg-1" onclick="get_all_api_list()">Filter</button>
            </div>
        </form>
    </div>

    <div class="mt-2 container-fluid border border-1 rounded-1 p-4">
        <div class="d-flex gap-2 justify-content-end align-items-center mb-2">
            <a class="btn btn-sm btn-secondary py-2" title="Go back to roles" href="{{ url_for('shared.create_roles') }}"><i class="fas fa-angle-left text-sm"></i> Go Back</a>
            <button type="button" class="btn btn-success" id="btn_create_api" data-bs-toggle="modal" data-bs-target="#addAPIModal"><i class="fa-solid fa-plus"></i> Create</button>
        </div>
        
        <div class="table-responsive small">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">Role</th>
                        <th scope="col">API</th>
                        <th scope="col">Type</th>
                        <th scope="col">Created At</th>
                        <th class="text-end" scope="col">Action</th>
                    </tr>
                </thead>
                <tbody id="tbody_api_list">
                    <!-- table body data will add by js -->
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Create API Modal -->
<div class="modal fade" id="addAPIModal" tabindex="-1" aria-labelledby="addAPIModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fs-6" id="addAPIModalLabel">Create API</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">

            <div class="form-group">
                <label for="api_role_name" class="mb-2 text-muted">Role</label>
                <input type="text" class="form-control" value="{{ set_role_name or '' }}" id="api_role_name" placeholder="Role Name">
                <ul id="suggestionRoles" class="list-group mt-2"></ul>
            </div>

            <div class="form-group mt-2">
                <label for="api_type" class="mb-2 text-muted">API Type</label>
                <select class="form-control" id="api_type">
                    <option value="GET" selected>GET</option>
                    <option value="POST">POST</option>
                    <option value="PUT">PUT</option>
                    <option value="HEAD">HEAD</option>
                    <option value="DELETE">DELETE</option>
                    <option value="PATCH">PATCH</option>
                    <option value="OPTIONS">OPTIONS</option>
                    <option value="CONNECT">CONNECT</option>
                    <option value="TRACE">TRACE</option>
                </select>
            </div>
            <div class="form-group mt-2">
                <label for="api_link_text" class="mb-2 text-muted">API Link</label>
                <input type="text" class="form-control" id="api_link_text" placeholder="API">
            </div>
            <div class="form-group mt-2">
                <label for="api_details" class="mb-2 text-muted">Details <span class="text-secondary">(Optional)</span></label>
                <textarea class="form-control" id="api_details" rows="3" placeholder="Details"></textarea>
            </div>

            <div class="d-flex justify-content-end mt-3">
                <button type="button" class="btn btn-success" onclick="create_api()"><i class="fas fa-plus text-sm"></i>&nbsp;Create</button>
            </div>

        </div>
      </div>
    </div>
</div>

<!-- Update API Modal -->
<div class="modal fade" id="updateAPIModal" tabindex="-1" aria-labelledby="updateAPIModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fs-6" id="updateAPIModalLabel">Update <span id="up_role"></span> (<span id="up_role_id"></span>) API</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">

            <div class="form-group">
                <label for="up_api_role_name" class="mb-2 text-muted">Role</label>
                <input type="text" class="form-control" value="{{ set_role_name or '' }}" id="up_api_role_name" placeholder="Role Name">
                <ul id="suggestionUpdateRoles" class="list-group mt-2"></ul>
            </div>

            <div class="form-group mt-2">
                <label for="update_api_type" class="mb-2 text-muted">API Type</label>
                <select class="form-control" id="update_api_type">
                    <option value="GET" selected>GET</option>
                    <option value="POST">POST</option>
                    <option value="PUT">PUT</option>
                    <option value="HEAD">HEAD</option>
                    <option value="DELETE">DELETE</option>
                    <option value="PATCH">PATCH</option>
                    <option value="OPTIONS">OPTIONS</option>
                    <option value="CONNECT">CONNECT</option>
                    <option value="TRACE">TRACE</option>
                </select>
            </div>
            <div class="form-group mt-2">
                <label for="update_api_link_text" class="mb-2 text-muted">API Link</label>
                <input type="text" class="form-control" id="update_api_link_text" placeholder="API">
            </div>
            <div class="form-group mt-2">
                <label for="update_api_details" class="mb-2 text-muted">Details <span class="text-secondary">(Optional)</span></label>
                <textarea class="form-control" id="update_api_details" rows="3" placeholder="Details"></textarea>
            </div>

            <div class="d-flex justify-content-end mt-3">
                <button type="button" class="btn btn-success" onclick="updateApiData()"><i class="fa-solid fa-arrow-up"></i>&nbsp;Update</button>
            </div>

        </div>
      </div>
    </div>
</div>

<!-- set if url has role name -->
<span style="display: none;" id="APIRoleName">{{ set_role_name or '' }}</span>
{% endblock %}


{% block scripts %}
    <script src="../../static/js/api_list.js"></script>
{% endblock %}

app/templates/users/createaccount.html
{% extends "base.html" %}
{% block title %}Create User Account{% endblock %}

{% block content %}
<div class="m-2">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center ms-2 pt-2 pb-3">
        <h4 >Create User Account</h4>
    </div>

    <div class="container-fluid border border-1 rounded-1 p-4">
        <form>
            <div class="row">
                <div class="form-group col-lg-6">
                    <label for="user_username" class="text-muted mb-1">Username</label>
                    <input type="text" class="form-control" id="user_username" placeholder="Username">
                </div>
                <div class="form-group col-lg-6">
                    <label for="userType" class="text-muted mb-1">User Type</label>
                    <select class="form-control" id="userType">
                        <option value="">Select Type</option>
                        <option value="Admin" {% if current_user.type == 'Admin' %} disabled {% endif %}>Admin</option>
                        <option value="API">API</option>
                    </select>
                </div>
            </div>

            <div class="row mt-2">
                <div class="form-group col-lg-6">
                    <label for="user_password" class="text-muted mb-1">Password</label>
                    <input type="password" class="form-control" id="user_password" placeholder="Password">
                </div>
                <div class="form-group col-lg-6">
                    <label for="user_confirmPassword" class="text-muted mb-1">Confirm Password</label>
                    <input type="password" class="form-control" id="user_confirmPassword" placeholder="Confirm Password">
                </div>
            </div>

            <div class="form-group mt-2">
                <label for="ac_role_name" class="text-muted mb-1">Roles</label>
                <select class="js-example-basic-multiple form-control" id="ac_role_name" name="user_roles[]" multiple="multiple">
                    <!-- option will ad by js -->
                </select>
            </div>

            <div class="row mt-2">
                <div class="form-group col-lg-6">
                    <label for="user_email" class="text-muted mb-1">Email <span class="text-secondary">(optional)</span></label>
                    <input type="email" class="form-control" id="user_email" placeholder="Email">
                </div>
                <div class="form-group col-lg-6">
                    <label for="user_phone" class="text-muted mb-1">Phone <span class="text-secondary">(optional)</span></label>
                    <input type="text" class="form-control" id="user_phone" placeholder="Phone">
                </div>
            </div>
            
            <div class="form-group mt-2">
              <label for="user_details" class="text-muted mb-1">Details <span class="text-secondary">(optional)</span></label>
              <textarea class="form-control" id="user_details" rows="3" placeholder="Details"></textarea>
            </div>

            <div class="d-flex justify-content-end mt-2">
                <button type="button" class="btn btn-success" onclick="create_api_user()"><i class="fa-solid fa-plus text-sm"></i> Create</button>
            </div>
        </form>
    </div>

</div>
{% endblock %}

{% block scripts %}
    <script src="../../static/js/account.js"></script>
{% endblock %}

app/templates/users/createroles.html
{% extends "base.html" %}
{% block title %}Create Roles{% endblock %}

{% block content %}
<div class="m-2">

    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center ms-2 pt-2 pb-3">
        <h4 >Roles</h4>
    </div>

    <div class="container-fluid border border-1 rounded-1 p-4">
        <div class="row my-2">
            <div class="col-6 p-0">
                <select class="js-example-basic-single form-control" id="filter_role_name" name="state">
                    <!-- option will ad by js -->
                </select>
            </div>

            <div class="col-6">
                <input type="text" class="form-control" id="filter_created_by" placeholder="Enter Create By" style="padding: 0.1rem .75rem !important;">
            </div>
        </div>
        <div class="d-flex gap-2 justify-content-end my-2">
            <button type="submit" class="btn btn-outline-secondary col-lg-1" onclick="reset_role_filter()">Reset</button>
            <button type="button" class="btn btn-primary col-lg-1" onclick="get_roles_list()">Filter</button>
        </div>
    </div>

    <div class="mt-2 container-fluid border border-1 rounded-1 p-4">
        <div class="d-flex justify-content-end mb-2">
            <button type="submit" class="btn btn-success" title="Create Role" data-bs-toggle="modal" data-bs-target="#createRoleModal"><i class="fa-solid fa-plus"></i> Create</button>
        </div>

        <div class="table-responsive small">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">Role</th>
                        <th scope="col">Created By</th>
                        <th scope="col">Created At</th>
                        <th class="text-end" scope="col">Action</th>
                    </tr>
                </thead>
                <tbody id="tbody_roles_list">
                    <!-- table body data will add by js -->
                </tbody>
            </table>
        </div>
    </div>
</div>


<!-- Create Role Modal -->
<div class="modal fade" id="createRoleModal" tabindex="-1" aria-labelledby="createRoleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title fs-6" id="createRoleModalLabel">Create Role Name</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">        

            <div class="form-group mt-2">
                <label for="api" class="mb-2 text-muted">Role Name</label>
                <input type="text" class="form-control" id="role_name" placeholder="Enter Role Name">
            </div>

            <div class="d-flex justify-content-end mt-3">
                <button type="button" class="btn btn-primary" onclick="create_role_name($('#role_name'))"><i class="fa-solid fa-plus text-sm"></i> Create</button>
            </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script>
        const apiListUrl = "{{ url_for('shared.api_list') }}";
    </script>
    <script src="../../static/js/roles.js"></script>
{% endblock %}

app/templates/users/dashboard.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock %} {% block
content %}
  <div class="m-2">
    <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center ms-2 pt-2 pb-3">
        <h4 >Hello, <span class="text-warning">{{ current_user.username }}</span>.
          welcome to User, Role & API Management dashboard.</h4>
    </div>

    <div class="container-fluid">
      <ul class="list-group">
        <!-- Create superuser link -->
        <li class="list-group-item">
            <strong>1. Create Superuser Link:</strong> 
            <a href="domain-name/create_superuser" target="_blank" class="text-decoration-none">domain-name/create_superuser</a><br>
            <strong>Method:</strong> POST<br>
            <strong>Body:</strong> 
            <pre>
              {
                "username": "example_user_admin",
                "password": "12345",
                "type": "Admin"
              }
            </pre>
        </li>
    
        <!-- Login API type user link -->
        <li class="list-group-item">
            <strong>2. Login (API type user) Link:</strong> 
            <a href="domain-name/api/login_api_user" target="_blank" class="text-decoration-none">domain-name/api/login_api_user</a><br>
            <strong>Method:</strong> POST<br>
            <strong>Body:</strong> 
            <pre>
              {
                "username": "example_user_api",
                "password": "12345"
              }
            </pre>
        </li>
    
        <!-- Get user roles API information -->
        <li class="list-group-item">
            <strong>3. Get User Roles API's Information:</strong> 
            <a href="domain-name/api/users_roles_apis_data" target="_blank" class="text-decoration-none">domain-name/api/users_roles_apis_data</a><br>
            <strong>Method:</strong> GET<br>
            <strong>Bearer Token:</strong> token-value
        </li>
    </ul>
    
    </div>
  </div>
{% endblock %}

app/templates/users/signin.html
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
  <script src="../../static/js/color-modes.js"></script>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.122.0">
  <title>URM- Signin</title>

<link rel="stylesheet" href="">
  <link href="../../static/css/bootstrap/bootstrap.min.css" rel="stylesheet">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="../../static/css/sign-in.css" rel="stylesheet">
</head>

<body class="d-flex align-items-center py-4 bg-body-tertiary">

  <main class="form-signin w-100 m-auto">
    <form action="{{ url_for('shared.signin_view') }}" method="POST">
      <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

      <div class="form-floating">
        <input type="text" class="form-control" name="username" id="floatingInput" placeholder="Username" required>
        <label for="floatingInput">Username</label>
      </div>
      <div class="form-floating">
        <input type="password" class="form-control" name="password" id="floatingPassword" placeholder="Password" required>
        <label for="floatingPassword">Password</label>
      </div>

      <!-- <div class="form-check text-start my-3">
        <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
          Remember me
        </label>
      </div> -->
      <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
      <p class="mt-3 mb-3 w-600 text-body-secondary text-center">Quant FinTach Limited&copy; <span id="year"></span></p>
    </form>
  </main>

  {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
          <div id="msg_text" style="display:none;">{{ message }}</div>
        {% endfor %}
      {% endif %}
  {% endwith %}

  <script src="../../static/js/bootstrap/bootstrap.bundle.min.js"></script>
  <script src="../../static/js/jquery-3.4.1.min.js"></script>
  <script src="../../static/js/tata.js"></script>
  <script>
    const currentYear = new Date().getFullYear();
    document.getElementById("year").textContent = currentYear;

    if ($('#msg_text').text() != '') {
      tata.error('Notification', $('#msg_text').text(), {
        position: 'tr',
        duration: 2000
      })
    }
  </script>


</body>

</html>